<?xml version="1.0" encoding="UTF-8"?>
<testExecutions version="1">
  <file path="C:\Users\Mattia\Desktop\spg\server\tests\apis.spec.js">
    <testCase name="tests GET /api/products" duration="48"/>
    <testCase name="tests GET /api/clients" duration="14"/>
    <testCase name="tests GET /api/clients/:id" duration="10"/>
    <testCase name="tests PUT /api/clients/:id/wallet" duration="48"/>
    <testCase name="tests POST /api/addNewUser" duration="290"/>
    <testCase name="tests error POST /api/addNewUser" duration="17"/>
    <testCase name="tests delete /api/sessions/current" duration="8"/>
    <testCase name="tests get /api/sessions/current" duration="7"/>
    <testCase name="tests get /api/nextProducts without performing the login" duration="61"/>
    <testCase name="tests get /api/nextProducts after the login as a customer not on sunday" duration="113">
      <failure message="Error: expected 200 &quot;OK&quot;, got 401 &quot;Unauthorized&quot;"><![CDATA[Error: expected 200 "OK", got 401 "Unauthorized"
    at Object.<anonymous> (C:\Users\Mattia\Desktop\spg\server\tests\apis.spec.js:183:61)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
----
    at Test.Object.<anonymous>.Test._assertStatus (C:\Users\Mattia\Desktop\spg\server\node_modules\supertest\lib\test.js:304:12)
    at C:\Users\Mattia\Desktop\spg\server\node_modules\supertest\lib\test.js:80:15
    at Test.Object.<anonymous>.Test._assertFunction (C:\Users\Mattia\Desktop\spg\server\node_modules\supertest\lib\test.js:338:11)
    at Test.Object.<anonymous>.Test.assert (C:\Users\Mattia\Desktop\spg\server\node_modules\supertest\lib\test.js:209:21)
    at Server.localAssert (C:\Users\Mattia\Desktop\spg\server\node_modules\supertest\lib\test.js:167:12)
    at Object.onceWrapper (events.js:482:28)
    at Server.emit (events.js:376:20)
    at emitCloseNT (net.js:1659:8)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)]]></failure>
    </testCase>
    <testCase name="tests post /api/sesion" duration="85"/>
    <testCase name="tests post /api/sesion error" duration="76"/>
    <testCase name="tests PUT /api/clients/basket/:id" duration="8"/>
    <testCase name="tests GET /api/wallet/:id" duration="7">
      <failure message="TypeError: response.body.forEach is not a function"><![CDATA[TypeError: response.body.forEach is not a function
    at Object.<anonymous> (C:\Users\Mattia\Desktop\spg\server\tests\apis.spec.js:296:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)]]></failure>
    </testCase>
  </file>
</testExecutions>